### ISSUE TITLE
Question regarding sample conversion 

### ISSUE THREAD

**Issue by ricardomatias** [geom3trik/tuix_audio_synth#4]
I hope it's okay to ask a question here.. Why is it necessary to convert a f32 to a cpal::Sample? Does it offer some kind of safeguards? 

```rust
// Convert the make_noise output into a sample
let value: T = cpal::Sample::from::<f32>(&make_noise(phi));
```

**Comment by geom3trik** [comment]
> I hope it's okay to ask a question here.. Why is it necessary to convert a f32 to a cpal::Sample? Does it offer some kind of safeguards?
> 
> ```rust
> // Convert the make_noise output into a sample
> let value: T = cpal::Sample::from::<f32>(&make_noise(phi));
> ```

The reason this is needed is because the `run()` function is generic on `T`, which is the sample type. For simplicity the `make_noise()` function is not generic so it returns an `f32` value. In order to convert it to the right sample type we use the `Sample::from()` method.

`cpal::Sample` is a trait, not a type, and is implemented for `i16`, `u16`, and `f32` types. The `from()` method will convert what you pass to it from, in this case `f32`, to the `T` type, which is why the `T` type is specified on the left hand side of the expression, so the compiler can figure out what we're trying to convert it to.

I hope that makes sense, let me know if you require further explanation.

**Comment by ricardomatias** [comment]
This makes perfect sense, thanks for the thorough explanation
